package truman.java.example.ser_obj_bytes_conv;

import java.io.Serializable;

public class MyData implements Serializable {

    private static final long serialVersionUID = -7534428891093065478L; // generated by local IDE

    private String name;
    private int age;
    private String company;
    private transient byte[] password; // Transient - Will be restored as default value, null

    public MyData(String name, int age, String company, byte[] password) {
        this.name = name;
        this.age = age;
        this.company = company;
        this.password = password;
    }

    public String getName() {
        return name;
    }

    public int getAge() {
        return age;
    }

    public String getCompany() {
        return company;
    }

    public byte[] getPassword() {
        return password;
    }

    public String toString() {
        return "Name : " + name + ", Age : " + age + ", Company : " + company +
                ", Password : " + (password == null ? "null" : new String(password));
    }
}